#!/usr/bin/env bash

###
### git-extend: Extend Git builtins with command wrappers.
###

PREFIX="/usr/local"
BINDIR="$PREFIX/bin"
GIT="$BINDIR/git"
ARGV=()

for ARG in "$@"; do
	case $ARG in
		extend)
			# @todo: Build out git-extend options.
			exit 0
		;;
		--bypass)
			BYPASS=1
		;;
		*)
			ARGV+=("$ARG")
		;;
	esac
done

# Reset $@ without git-extend(1) options.
set -- "${ARGV[@]}"
unset ARGV
unset ARG

if [[ -n $TLPID ]] && [[ $TLPID -eq $PPID ]]; then
	BYPASS=1
fi

if [[ -n $BYPASS ]] && [[ $BYPASS -eq 1 ]]; then
	$GIT "$@"

	exit $?
fi

# Top-level PID.
export TLPID="$$"

# Pathnames from $PATH.
SCOPES="$(echo $PATH | tr ':' '\n')"

for PATHNAME in ${SCOPES[@]}; do
	ARGV=("$@")
	COUNT=0

	while [[ ${#ARGV[@]} -gt 0 ]]; do
		TARGET="$PATHNAME/git-${ARGV[0]}"

		if [[ -x "$TARGET" ]]; then
			# Executable path with git(1) options, arguments (e.g. '/usr/bin/git -C ~/project').
			# $GIT should be called from within the command wrappers to ensure proper handling.
			export GIT="$GIT ${@:1:COUNT}"

			# Execute $TARGET with command-specific arguments only.
			$TARGET "${ARGV[@]:1}"

			exit $?
		fi

		ARGV=("${ARGV[@]:1}")
		let COUNT++
	done
done

$GIT "$@"
