#!/usr/bin/env bash

###
### git-diff: Add convenience options to git-diff(1).
###

ERR_NOTREPO="Not a Git repository."

# Implicit options.
ARGV=(
	"--minimal"
)

while [[ $# -gt 0 ]]; do
	case $1 in
		-h|--help)
			exec $GIT diff --help

			exit 0
		;;
		--color)
			shift

			ARGV+=("--word-diff=color")
		;;
		--sxs)
			shift

			ARGV+=("--word-diff=plain")
		;;
		*)
			ARGV+=("$1")

			shift
		;;
	esac
done

if [[ ! "$($GIT rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
	printf '%s: %s\n' "$0" "$ERR_NOTREPO"

	exit 1
fi

exec $GIT diff ${ARGV[@]}
