#!/usr/bin/env bash

###
### git-add: Add convenience options to git-add(1).
###

ERR_NOTREPO="Not a Git repository."

if [[ ! "$(git rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
	printf '%s\n' "$ERR_NOTREPO"

	exit 1
fi

ARGV=()
FILES=()
REGEX='^%[0-9]+$'
STAGEABLE=()

UNSTAGED="$(git status --porcelain=v1 | grep -E '^(\w|\s)(M|A|D|R|C|U)\s+' | awk '{$1=$1};1' | cut -d' ' -f2)"

# Add unstaged files to stageable list.
for FILE in ${UNSTAGED[@]}; do
	STAGEABLE+=("$FILE")
done

UNTRACKED="$(git status --porcelain=v1 | grep '??' | cut -d' ' -f2)"

# Add untracked files to stageable list.
for FILE in ${UNTRACKED[@]}; do
	STAGEABLE+=("$FILE")
done

while [[ $# -gt 0 ]]; do
	case $1 in
		%*)
			INDEX="$1"

			if [[ ! "$INDEX" =~ $REGEX ]]; then
				printf 'Invalid format given for entry index.\n' "$INDEX"

				exit 1
			fi

			INDEX="$(( $(echo $INDEX | tr -d '%') - 1 ))"

			if [[ $INDEX -lt 0 ]] || [[ $(expr $INDEX + 1) -gt ${#STAGEABLE[@]}  ]]; then
				printf '%s is not a valid index.\n' "$(expr $INDEX + 1)"

				exit 1
			fi

			FILES+=("${STAGEABLE[$INDEX]}")

			shift
		;;
		*)
			ARGV+=("$1")

			shift
		;;
	esac
done

git add "${ARGV[@]}" "${FILES[@]}"
