#!/usr/bin/env bash

###
### git-status: Add convenience options to git-status(1).
###

ERR_NOTREPO="Not a Git repository."

# Implicit options.
ARGV=()

while [[ $# -gt 0 ]]; do
	case $1 in
		--help|-h)
			git status --help

			exit 0
		;;
		--numbered|-N)
			if [[ ! "$($GIT rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
				echo "$ERR_NOTREPO"

				exit 1
			fi

			COUNT=0

			# Prepend index # to pathspec.
			$GIT status -s | while read LINE; do
				let "COUNT++"

				echo "${COUNT}. $LINE"
			done

			exit 0
		;;
		*)
			ARGV+=("$1")

			shift
		;;
	esac
done

if [[ ! "$($GIT rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
	echo "$ERR_NOTREPO"

	exit 1
fi

$GIT status "${ARGV[@]}"
