#!/usr/bin/env bash

###
### git-log: Add convenience options and default pretty format to git-log(1).
###

ERR_NOTREPO="Not a Git repository."

# Decorated `git log` graph format style.
FORMAT="%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset"
NUM="10"
REGEX='^[0-9]+$'
ARGV=(
	"--graph"
	"--abbrev-commit"
	"--date=relative"
	"--format=$FORMAT"
	"--max-count=$NUM"
)

while [[ $# -gt 0 ]]; do
	case $1 in
		--help|-h)
			$GIT log --help

			exit 0
		;;
		--all|-A)
			shift

			if [[ ! "$($GIT rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
				printf '%s\n' "$ERR_NOTREPO"

				exit 1
			fi

			[[ -z "$TOTAL" ]] && TOTAL="$($GIT rev-list HEAD --count)"

			ARGV+=("--max-count=$TOTAL")
		;;
		--last)
			shift

			if [[ ! "$($GIT rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
				printf '%s\n' "$ERR_NOTREPO"

				exit 1
			fi

			NUM="$1"

			[[ -z "$TOTAL" ]] && TOTAL="$($GIT rev-list HEAD --count)"
			[[ ! $NUM =~ $REGEX ]] && NUM=1
			[[ $NUM -gt $TOTAL ]] && NUM="$TOTAL"

			ARGV+=("--max-count=$NUM")

			shift
		;;
		*)
			ARGV+=("$1")

			shift
		;;
	esac
done

if [[ ! "$($GIT rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
	printf '%s\n' "$ERR_NOTREPO"

	exit 1
fi

$GIT log "${ARGV[@]}"
