#!/usr/bin/env bash

###
### git-log: Add convenience options and default pretty format to git-log(1).
###

ERR_NOTREPO="Not a Git repository."

if [[ ! "$(git rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
	printf '%s\n' "$ERR_NOTREPO"

	exit 1
fi

# Total number of commits for the repository.
TOTAL="$(git rev-list HEAD --count)"

# Decorated `git log` graph format style.
FORMAT="%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset"
NUM="10"
REGEX='^[0-9]+$'
ARGV=(
	"--graph"
	"--abbrev-commit"
	"--date=relative"
	"--format=$FORMAT"
	"--max-count=$NUM"
)

while [[ $# -gt 0 ]]; do
	case $1 in
		--help|-h)
			git log --help

			exit 0
		;;
		--all|-a)
			shift

			ARGV+=("--max-count=$TOTAL")

			shift
		;;
		--last|-l)
			shift

			NUM="$1"

			if [[ ! $NUM =~ $REGEX ]]; then
				NUM="1"
			fi

			if [[ $NUM -gt $TOTAL ]]; then
				NUM="$TOTAL"
			fi

			ARGV+=("--max-count=$NUM")

			shift
		;;
		*)
			ARGV+=("$1")

			shift
		;;
	esac
done

$GIT log "${ARGV[@]}"
