#!/usr/bin/env bash

###
### git-diff: Add convenience options to git-diff(1).
###

# Implicit options.
ARGV=(
	"--color-words"
	"--minimal"
)

while [[ $# -gt 0 ]]; do
	case $1 in
		--help|-h)
			git diff --help

			exit 0
		;;
		--inline|-i)
			shift

			ARGV+=("--word-diff=plain")
		;;
		*)
			ARGV+=("$1")

			shift
		;;
	esac
done

if [[ ! "$($GIT rev-parse --is-inside-work-tree)" ]] 2>/dev/null; then
	echo "Not a Git repository."

	exit 1
fi

$GIT diff "${ARGV[@]}"
